//elementosTabela.js
const elementosDaTabelaPeriodica = [
  {
    atomic_number: 1,
    symbol: "H",
    name: "Hidrogênio",
    atomic_mass: 1.008,
    group: 1,
    period: 1,
    block: "s",
    electron_configuration: "1s¹",
    electronegativity: 2.2,
    phase: "Gás",
    category: "Não Metal",
    description:
      "O hidrogênio é o elemento químico mais leve e abundante do universo. É um gás incolor, inodoro e insípido.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 2,
    symbol: "He",
    name: "Hélio",
    atomic_mass: 4.0026,
    group: 18,
    period: 1,
    block: "s",
    electron_configuration: "1s²",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O hélio é o segundo elemento mais leve e o segundo mais abundante no universo, sendo inerte e usado em balões e criogenia.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 3,
    symbol: "Li",
    name: "Lítio",
    atomic_mass: 6.94,
    group: 1,
    period: 2,
    block: "s",
    electron_configuration: "[He] 2s¹",
    electronegativity: 0.98,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O lítio é um metal alcalino macio, prateado-branco, usado em baterias de íon-lítio.",
    color: "#fef08a",
  },
  {
    atomic_number: 4,
    symbol: "Be",
    name: "Berílio",
    atomic_mass: 9.0121831,
    group: 2,
    period: 2,
    block: "s",
    electron_configuration: "[He] 2s²",
    electronegativity: 1.57,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O berílio é um metal alcalino-terroso leve e rígido, usado em ligas e componentes aeroespaciais.",
    color: "#fcd34d",
  },
  {
    atomic_number: 5,
    symbol: "B",
    name: "Boro",
    atomic_mass: 10.81,
    group: 13,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O boro é um semimetal com propriedades entre o metal e o não metal, usado em vidros, cerâmicas e semicondutores.",
    color: "#d1d5db",
  },
  {
    atomic_number: 6,
    symbol: "C",
    name: "Carbono",
    atomic_mass: 12.011,
    group: 14,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p²",
    electronegativity: 2.55,
    phase: "Sólido",
    category: "Não Metal",
    description:
      "O carbono é um elemento químico com o símbolo C e número atômico 6. É a base da vida na Terra.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 7,
    symbol: "N",
    name: "Nitrogênio",
    atomic_mass: 14.007,
    group: 15,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p³",
    electronegativity: 3.04,
    phase: "Gás",
    category: "Não Metal",
    description:
      "O nitrogênio é o componente principal do ar atmosférico, um gás inerte e vital para a vida.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 8,
    symbol: "O",
    name: "Oxigênio",
    atomic_mass: 15.999,
    group: 16,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    phase: "Gás",
    category: "Não Metal",
    description:
      "O oxigênio é um elemento químico essencial para a respiração da maioria dos organismos e suporta a combustão.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 9,
    symbol: "F",
    name: "Flúor",
    atomic_mass: 18.998403163,
    group: 17,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    phase: "Gás",
    category: "Halogênio",
    description:
      "O flúor é o halogênio mais reativo, um gás amarelo pálido altamente tóxico.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 10,
    symbol: "Ne",
    name: "Neônio",
    atomic_mass: 20.1797,
    group: 18,
    period: 2,
    block: "p",
    electron_configuration: "[He] 2s² 2p⁶",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O neônio é um gás nobre inerte usado em letreiros luminosos, produzindo uma luz vermelho-alaranjada.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 11,
    symbol: "Na",
    name: "Sódio",
    atomic_mass: 22.98976928,
    group: 1,
    period: 3,
    block: "s",
    electron_configuration: "[Ne] 3s¹",
    electronegativity: 0.93,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O sódio é um metal alcalino macio e reativo, vital para muitos processos biológicos.",
    color: "#fef08a",
  },
  {
    atomic_number: 12,
    symbol: "Mg",
    name: "Magnésio",
    atomic_mass: 24.305,
    group: 2,
    period: 3,
    block: "s",
    electron_configuration: "[Ne] 3s²",
    electronegativity: 1.31,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O magnésio é um metal alcalino-terroso leve e forte, usado em ligas estruturais e pirotecnia.",
    color: "#fcd34d",
  },
  {
    atomic_number: 13,
    symbol: "Al",
    name: "Alumínio",
    atomic_mass: 26.9815384,
    group: 13,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O alumínio é um metal pós-transição leve, durável e resistente à corrosão, amplamente usado.",
    color: "#d9f99d",
  },
  {
    atomic_number: 14,
    symbol: "Si",
    name: "Silício",
    atomic_mass: 28.085,
    group: 14,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O silício é um semimetal usado extensivamente em eletrônica (semicondutores) e cerâmica.",
    color: "#d1d5db",
  },
  {
    atomic_number: 15,
    symbol: "P",
    name: "Fósforo",
    atomic_mass: 30.973761998,
    group: 15,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    phase: "Sólido",
    category: "Não Metal",
    description:
      "O fósforo é um não metal reativo, essencial para a vida (DNA, ATP) e usado em fertilizantes e explosivos.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 16,
    symbol: "S",
    name: "Enxofre",
    atomic_mass: 32.06,
    group: 16,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    phase: "Sólido",
    category: "Não Metal",
    description:
      "O enxofre é um não metal abundante, amarelo, usado em ácidos, fertilizantes e pólvora.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 17,
    symbol: "Cl",
    name: "Cloro",
    atomic_mass: 35.45,
    group: 17,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    phase: "Gás",
    category: "Halogênio",
    description:
      "O cloro é um halogênio, um gás amarelo-esverdeado tóxico usado como desinfetante e em produtos químicos.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 18,
    symbol: "Ar",
    name: "Argônio",
    atomic_mass: 39.948,
    group: 18,
    period: 3,
    block: "p",
    electron_configuration: "[Ne] 3s² 3p⁶",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O argônio é um gás nobre inerte, o terceiro gás mais comum na atmosfera da Terra, usado em iluminação e soldagem.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 19,
    symbol: "K",
    name: "Potássio",
    atomic_mass: 39.0983,
    group: 1,
    period: 4,
    block: "s",
    electron_configuration: "[Ar] 4s¹",
    electronegativity: 0.82,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O potássio é um metal alcalino macio e reativo, essencial para a função celular e usado em fertilizantes.",
    color: "#fef08a",
  },
  {
    atomic_number: 20,
    symbol: "Ca",
    name: "Cálcio",
    atomic_mass: 40.078,
    group: 2,
    period: 4,
    block: "s",
    electron_configuration: "[Ar] 4s²",
    electronegativity: 1.0,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O cálcio é um metal alcalino-terroso, vital para ossos e dentes, usado em cimento e argamassa.",
    color: "#fcd34d",
  },
  {
    atomic_number: 21,
    symbol: "Sc",
    name: "Escândio",
    atomic_mass: 44.955908,
    group: 3,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O escândio é um metal de transição leve, usado em ligas de alumínio para componentes aeroespaciais.",
    color: "#bae6fd",
  },
  {
    atomic_number: 22,
    symbol: "Ti",
    name: "Titânio",
    atomic_mass: 47.867,
    group: 4,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O titânio é um metal de transição forte, leve e resistente à corrosão, usado em aeroespacial, médico e esportes.",
    color: "#bae6fd",
  },
  {
    atomic_number: 23,
    symbol: "V",
    name: "Vanádio",
    atomic_mass: 50.9415,
    group: 5,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O vanádio é um metal de transição duro e prateado, usado em ligas de aço para aumentar a resistência.",
    color: "#bae6fd",
  },
  {
    atomic_number: 24,
    symbol: "Cr",
    name: "Cromo",
    atomic_mass: 51.9961,
    group: 6,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O cromo é um metal de transição brilhante e duro, usado em aço inoxidável, cromagem e pigmentos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 25,
    symbol: "Mn",
    name: "Manganês",
    atomic_mass: 54.938044,
    group: 7,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O manganês é um metal de transição importante em ligas de aço para resistência e durabilidade.",
    color: "#bae6fd",
  },
  {
    atomic_number: 26,
    symbol: "Fe",
    name: "Ferro",
    atomic_mass: 55.845,
    group: 8,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O ferro é um metal de transição fundamental, a base do aço e essencial na hemoglobina.",
    color: "#bae6fd",
  },
  {
    atomic_number: 27,
    symbol: "Co",
    name: "Cobalto",
    atomic_mass: 58.933194,
    group: 9,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O cobalto é um metal de transição ferromagnético, usado em ligas de alta resistência, baterias e pigmentos azuis.",
    color: "#bae6fd",
  },
  {
    atomic_number: 28,
    symbol: "Ni",
    name: "Níquel",
    atomic_mass: 58.6934,
    group: 10,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O níquel é um metal de transição prateado-branco, usado em aço inoxidável, moedas e baterias.",
    color: "#bae6fd",
  },
  {
    atomic_number: 29,
    symbol: "Cu",
    name: "Cobre",
    atomic_mass: 63.546,
    group: 11,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O cobre é um metal de transição com alta condutividade elétrica e térmica, usado em fios e tubulações.",
    color: "#bae6fd",
  },
  {
    atomic_number: 30,
    symbol: "Zn",
    name: "Zinco",
    atomic_mass: 65.38,
    group: 12,
    period: 4,
    block: "d",
    electron_configuration: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O zinco é um metal de transição usado para galvanizar aço, em ligas (latão) e baterias.",
    color: "#bae6fd",
  },
  {
    atomic_number: 31,
    symbol: "Ga",
    name: "Gálio",
    atomic_mass: 69.723,
    group: 13,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O gálio é um metal pós-transição que derrete perto da temperatura ambiente, usado em eletrônica (LEDs).",
    color: "#d9f99d",
  },
  {
    atomic_number: 32,
    symbol: "Ge",
    name: "Germânio",
    atomic_mass: 72.63,
    group: 14,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O germânio é um semimetal usado como semicondutor em eletrônica e em sistemas ópticos infravermelhos.",
    color: "#d1d5db",
  },
  {
    atomic_number: 33,
    symbol: "As",
    name: "Arsênio",
    atomic_mass: 74.921595,
    group: 15,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O arsênio é um semimetal tóxico usado em pesticidas, herbicidas e semicondutores.",
    color: "#d1d5db",
  },
  {
    atomic_number: 34,
    symbol: "Se",
    name: "Selênio",
    atomic_mass: 78.971,
    group: 16,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    phase: "Sólido",
    category: "Não Metal",
    description:
      "O selênio é um não metal com propriedades fotoelétricas, usado em eletrônica, fotocopiadoras e vidros.",
    color: "#a7f3d0",
  },
  {
    atomic_number: 35,
    symbol: "Br",
    name: "Bromo",
    atomic_mass: 79.904,
    group: 17,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    phase: "Líquido",
    category: "Halogênio",
    description:
      "O bromo é o único halogênio líquido à temperatura ambiente, um líquido vermelho-acastanhado volátil e tóxico.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 36,
    symbol: "Kr",
    name: "Criptônio",
    atomic_mass: 83.798,
    group: 18,
    period: 4,
    block: "p",
    electron_configuration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O criptônio é um gás nobre inerte, usado em alguns tipos de iluminação de alta intensidade.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 37,
    symbol: "Rb",
    name: "Rubídio",
    atomic_mass: 85.4678,
    group: 1,
    period: 5,
    block: "s",
    electron_configuration: "[Kr] 5s¹",
    electronegativity: 0.82,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O rubídio é um metal alcalino macio e altamente reativo, usado em aplicações científicas e células fotoelétricas.",
    color: "#fef08a",
  },
  {
    atomic_number: 38,
    symbol: "Sr",
    name: "Estrôncio",
    atomic_mass: 87.62,
    group: 2,
    period: 5,
    block: "s",
    electron_configuration: "[Kr] 5s²",
    electronegativity: 0.95,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O estrôncio é um metal alcalino-terroso macio, usado em pirotecnia (fogo vermelho) e na fabricação de ímãs.",
    color: "#fcd34d",
  },
  {
    atomic_number: 39,
    symbol: "Y",
    name: "Ítrio",
    atomic_mass: 88.90584,
    group: 3,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O ítrio é um metal de transição prateado, usado em ligas, emissores de luz (LEDs vermelhos) e supercondutores.",
    color: "#bae6fd",
  },
  {
    atomic_number: 40,
    symbol: "Zr",
    name: "Zircônio",
    atomic_mass: 91.224,
    group: 4,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O zircônio é um metal de transição resistente à corrosão, usado em reatores nucleares e cerâmicas.",
    color: "#bae6fd",
  },
  {
    atomic_number: 41,
    symbol: "Nb",
    name: "Nióbio",
    atomic_mass: 92.90637,
    group: 5,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O nióbio é um metal de transição refratário, usado em ligas de aço de alta resistência e supercondutores.",
    color: "#bae6fd",
  },
  {
    atomic_number: 42,
    symbol: "Mo",
    name: "Molibdênio",
    atomic_mass: 95.95,
    group: 6,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O molibdênio é um metal de transição refratário, usado em ligas de aço para aumentar a dureza e resistência ao calor.",
    color: "#bae6fd",
  },
  {
    atomic_number: 43,
    symbol: "Tc",
    name: "Tecnécio",
    atomic_mass: 96.90636,
    group: 7,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O tecnécio é o elemento mais leve sem isótopos estáveis, usado em medicina nuclear para diagnósticos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 44,
    symbol: "Ru",
    name: "Rutênio",
    atomic_mass: 101.07,
    group: 8,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O rutênio é um metal de transição raro, usado em ligas de platina e como catalisador.",
    color: "#bae6fd",
  },
  {
    atomic_number: 45,
    symbol: "Rh",
    name: "Ródio",
    atomic_mass: 102.9055,
    group: 9,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O ródio é um metal de transição raro e resistente à corrosão, usado em catalisadores automotivos e joias.",
    color: "#bae6fd",
  },
  {
    atomic_number: 46,
    symbol: "Pd",
    name: "Paládio",
    atomic_mass: 106.42,
    group: 10,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d¹⁰",
    electronegativity: 2.2,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O paládio é um metal de transição prateado, usado em catalisadores, eletrônica e joias.",
    color: "#bae6fd",
  },
  {
    atomic_number: 47,
    symbol: "Ag",
    name: "Prata",
    atomic_mass: 107.8682,
    group: 11,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "A prata é um metal de transição com alta condutividade elétrica e térmica, usado em joias, moedas e eletrônica.",
    color: "#bae6fd",
  },
  {
    atomic_number: 48,
    symbol: "Cd",
    name: "Cádmio",
    atomic_mass: 112.414,
    group: 12,
    period: 5,
    block: "d",
    electron_configuration: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O cádmio é um metal de transição tóxico usado em baterias (NiCd) e pigmentos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 49,
    symbol: "In",
    name: "Índio",
    atomic_mass: 114.818,
    group: 13,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O índio é um metal pós-transição macio, usado em ligas de baixo ponto de fusão e telas LCD.",
    color: "#d9f99d",
  },
  {
    atomic_number: 50,
    symbol: "Sn",
    name: "Estanho",
    atomic_mass: 118.71,
    group: 14,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O estanho é um metal pós-transição maleável, usado em soldas e revestimentos para prevenir corrosão.",
    color: "#d9f99d",
  },
  {
    atomic_number: 51,
    symbol: "Sb",
    name: "Antimônio",
    atomic_mass: 121.76,
    group: 15,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O antimônio é um semimetal usado em ligas (para dureza) e semicondutores.",
    color: "#d1d5db",
  },
  {
    atomic_number: 52,
    symbol: "Te",
    name: "Telúrio",
    atomic_mass: 127.6,
    group: 16,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O telúrio é um semimetal usado em semicondutores, painéis solares e borracha.",
    color: "#d1d5db",
  },
  {
    atomic_number: 53,
    symbol: "I",
    name: "Iodo",
    atomic_mass: 126.90447,
    group: 17,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    phase: "Sólido",
    category: "Halogênio",
    description:
      "O iodo é um halogênio sólido que sublima facilmente, essencial para a tireoide e usado como desinfetante.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 54,
    symbol: "Xe",
    name: "Xenônio",
    atomic_mass: 131.293,
    group: 18,
    period: 5,
    block: "p",
    electron_configuration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O xenônio é um gás nobre inerte, usado em lâmpadas de descarga de alta intensidade e anestesia.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 55,
    symbol: "Cs",
    name: "Césio",
    atomic_mass: 132.90545196,
    group: 1,
    period: 6,
    block: "s",
    electron_configuration: "[Xe] 6s¹",
    electronegativity: 0.79,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O césio é o metal alcalino não radioativo mais reativo, usado em relógios atômicos.",
    color: "#fef08a",
  },
  {
    atomic_number: 56,
    symbol: "Ba",
    name: "Bário",
    atomic_mass: 137.327,
    group: 2,
    period: 6,
    block: "s",
    electron_configuration: "[Xe] 6s²",
    electronegativity: 0.89,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O bário é um metal alcalino-terroso usado em fogos de artifício (cor verde) e radiografias médicas.",
    color: "#fcd34d",
  },
  {
    atomic_number: 57,
    symbol: "La",
    name: "Lantânio",
    atomic_mass: 138.90547,
    group: 3,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O lantânio é o primeiro elemento da série dos lantanídeos, usado em ligas e vidros especiais.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 58,
    symbol: "Ce",
    name: "Cério",
    atomic_mass: 140.116,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O cério é um lantanídeo usado em ligas (ferrocério, para faíscas) e polimento de vidro.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 59,
    symbol: "Pr",
    name: "Praseodímio",
    atomic_mass: 140.90766,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O praseodímio é um lantanídeo usado em ligas com magnésio e em vidros coloridos (verde e amarelo).",
    color: "#e9d5ff",
  },
  {
    atomic_number: 60,
    symbol: "Nd",
    name: "Neodímio",
    atomic_mass: 144.242,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O neodímio é um lantanídeo usado em ímãs permanentes poderosos e em vidros que bloqueiam raios infravermelhos.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 61,
    symbol: "Pm",
    name: "Promécio",
    atomic_mass: 144.91276,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O promécio é o único lantanídeo radioativo, usado em marcadores luminosos e baterias nucleares de pesquisa.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 62,
    symbol: "Sm",
    name: "Samário",
    atomic_mass: 150.36,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O samário é um lantanídeo usado em ímãs permanentes de alta temperatura e em barras de controle de reatores nucleares.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 63,
    symbol: "Eu",
    name: "Európio",
    atomic_mass: 151.964,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O európio é um lantanídeo usado em fósforos vermelhos para telas de TV e como ativador em materiais luminescentes.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 64,
    symbol: "Gd",
    name: "Gadolínio",
    atomic_mass: 157.25,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O gadolínio é um lantanídeo usado em ressonância magnética (MRI) e como blindagem contra nêutrons.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 65,
    symbol: "Tb",
    name: "Térbio",
    atomic_mass: 158.92535,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.1,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O térbio é um lantanídeo usado em fósforos verdes (telas de TV) e em dispositivos magneto-ópticos.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 66,
    symbol: "Dy",
    name: "Disprósio",
    atomic_mass: 162.5,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O disprósio é um lantanídeo usado em ímãs de alta resistência (com neodímio) e em ligas.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 67,
    symbol: "Ho",
    name: "Hólmio",
    atomic_mass: 164.93033,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O hólmio é um lantanídeo usado em lasers e em ligas com alto momento magnético.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 68,
    symbol: "Er",
    name: "Érbio",
    atomic_mass: 167.259,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O érbio é um lantanídeo usado em amplificadores ópticos (fibras ópticas) e vidros coloridos (rosa).",
    color: "#e9d5ff",
  },
  {
    atomic_number: 69,
    symbol: "Tm",
    name: "Túlio",
    atomic_mass: 168.93422,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹³ 6s²",
    electronegativity: 1.25,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O túlio é um lantanídeo usado em fontes de raios X portáteis e em alguns tipos de laser.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 70,
    symbol: "Yb",
    name: "Itérbio",
    atomic_mass: 173.045,
    group: 3,
    period: 6,
    block: "f",
    electron_configuration: "[Xe] 4f¹⁴ 6s²",
    electronegativity: 1.06,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O itérbio é um lantanídeo usado em ligas de aço inoxidável e em medidores de tensão.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 71,
    symbol: "Lu",
    name: "Lutécio",
    atomic_mass: 174.9668,
    group: 3,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: 1.2,
    phase: "Sólido",
    category: "Lantanídeo",
    description:
      "O lutécio é o último elemento da série dos lantanídeos, usado em catálise e datação por radiocarbono.",
    color: "#e9d5ff",
  },
  {
    atomic_number: 72,
    symbol: "Hf",
    name: "Háfnio",
    atomic_mass: 178.49,
    group: 4,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O háfnio é um metal de transição resistente à corrosão, usado em barras de controle de reatores nucleares e ligas.",
    color: "#bae6fd",
  },
  {
    atomic_number: 73,
    symbol: "Ta",
    name: "Tântalo",
    atomic_mass: 180.94788,
    group: 5,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: 1.5,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O tântalo é um metal de transição refratário e resistente à corrosão, usado em capacitores eletrônicos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 74,
    symbol: "W",
    name: "Tungstênio",
    atomic_mass: 183.84,
    group: 6,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: 2.36,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O tungstênio (ou volfrâmio) tem o maior ponto de fusão de todos os metais, usado em filamentos de lâmpadas e ferramentas de corte.",
    color: "#bae6fd",
  },
  {
    atomic_number: 75,
    symbol: "Re",
    name: "Rênio",
    atomic_mass: 186.207,
    group: 7,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: 1.9,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O rênio é um metal de transição raro e refratário, usado em superligas para turbinas a jato.",
    color: "#bae6fd",
  },
  {
    atomic_number: 76,
    symbol: "Os",
    name: "Ósmio",
    atomic_mass: 190.23,
    group: 8,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: 2.2,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O ósmio é o metal natural mais denso, usado em pontas de canetas-tinteiro e contatos elétricos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 77,
    symbol: "Ir",
    name: "Irídio",
    atomic_mass: 192.217,
    group: 9,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: 2.2,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O irídio é um metal de transição resistente à corrosão, usado em velas de ignição e pontas de canetas.",
    color: "#bae6fd",
  },
  {
    atomic_number: 78,
    symbol: "Pt",
    name: "Platina",
    atomic_mass: 195.084,
    group: 10,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: 2.28,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "A platina é um metal de transição nobre, usado em joias, catalisadores automotivos e equipamentos de laboratório.",
    color: "#bae6fd",
  },
  {
    atomic_number: 79,
    symbol: "Au",
    name: "Ouro",
    atomic_mass: 196.966569,
    group: 11,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "O ouro é um metal de transição valioso e maleável, usado em joias, moedas e eletrônicos.",
    color: "#bae6fd",
  },
  {
    atomic_number: 80,
    symbol: "Hg",
    name: "Mercúrio",
    atomic_mass: 200.59,
    group: 12,
    period: 6,
    block: "d",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.0,
    phase: "Líquido",
    category: "Metal de Transição",
    description:
      "O mercúrio é o único metal líquido à temperatura ambiente, tóxico, usado em termômetros e interruptores (uso diminuindo).",
    color: "#bae6fd",
  },

  {
    atomic_number: 81,
    symbol: "Tl",
    name: "Tálio",
    atomic_mass: 204.38,
    group: 13,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O tálio é um metal pós-transição macio e tóxico, usado em eletrônica (uso limitado devido à toxicidade).",
    color: "#d9f99d",
  },
  {
    atomic_number: 82,
    symbol: "Pb",
    name: "Chumbo",
    atomic_mass: 207.2,
    group: 14,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O chumbo é um metal pós-transição pesado, maleável e tóxico, usado em baterias, pesos e blindagem contra radiação.",
    color: "#d9f99d",
  },
  {
    atomic_number: 83,
    symbol: "Bi",
    name: "Bismuto",
    atomic_mass: 208.9804,
    group: 15,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    phase: "Sólido",
    category: "Metal Pós-Transição",
    description:
      "O bismuto é um metal pós-transição quebradiço, com baixo ponto de fusão, usado em medicamentos e ligas de baixo ponto de fusão.",
    color: "#d9f99d",
  },
  {
    atomic_number: 84,
    symbol: "Po",
    name: "Polônio",
    atomic_mass: 208.98243,
    group: 16,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    phase: "Sólido",
    category: "Semimetal",
    description:
      "O polônio é um semimetal altamente radioativo, usado em fontes de partículas alfa (uso limitado).",
    color: "#d1d5db",
  },
  {
    atomic_number: 85,
    symbol: "At",
    name: "Ástato",
    atomic_mass: 209.98715,
    group: 17,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    phase: "Sólido",
    category: "Halogênio",
    description:
      "O ástato é um halogênio extremamente radioativo e raro, com poucas aplicações práticas.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 86,
    symbol: "Rn",
    name: "Radônio",
    atomic_mass: 222.01757,
    group: 18,
    period: 6,
    block: "p",
    electron_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: null,
    phase: "Gás",
    category: "Gás Nobre",
    description:
      "O radônio é um gás nobre radioativo, formado pela decomposição do rádio, um risco à saúde em altas concentrações.",
    color: "#bfdbfe",
  },
  {
    atomic_number: 87,
    symbol: "Fr",
    name: "Frâncio",
    atomic_mass: 223.01973,
    group: 1,
    period: 7,
    block: "s",
    electron_configuration: "[Rn] 7s¹",
    electronegativity: 0.7,
    phase: "Sólido",
    category: "Metal Alcalino",
    description:
      "O frâncio é o segundo elemento natural mais raro na Terra, altamente radioativo, com pouca aplicação.",
    color: "#fef08a",
  },
  {
    atomic_number: 88,
    symbol: "Ra",
    name: "Rádio",
    atomic_mass: 226.02545,
    group: 2,
    period: 7,
    block: "s",
    electron_configuration: "[Rn] 7s²",
    electronegativity: 0.9,
    phase: "Sólido",
    category: "Metal Alcalino-Terroso",
    description:
      "O rádio é um metal alcalino-terroso altamente radioativo, descoberto por Marie Curie, usado anteriormente em tintas luminescentes.",
    color: "#fcd34d",
  },
  {
    atomic_number: 89,
    symbol: "Ac",
    name: "Actínio",
    atomic_mass: 227.02775,
    group: 3,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O actínio é o primeiro elemento da série dos actinídeos, altamente radioativo.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 90,
    symbol: "Th",
    name: "Tório",
    atomic_mass: 232.0377,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O tório é um actinídeo radioativo usado em mantas de gás e considerado um possível combustível nuclear.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 91,
    symbol: "Pa",
    name: "Protactínio",
    atomic_mass: 231.03588,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: 1.5,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O protactínio é um actinídeo raro, altamente radioativo e tóxico.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 92,
    symbol: "U",
    name: "Urânio",
    atomic_mass: 238.02891,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O urânio é um actinídeo radioativo, o principal combustível em reatores nucleares e em armas atômicas.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 93,
    symbol: "Np",
    name: "Netúnio",
    atomic_mass: 237.04817,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: 1.36,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O netúnio é o primeiro elemento transurânico, radioativo, produzido artificialmente.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 94,
    symbol: "Pu",
    name: "Plutônio",
    atomic_mass: 244.0642,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f⁶ 7s²",
    electronegativity: 1.28,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O plutônio é um actinídeo radioativo e tóxico, usado em armas nucleares e reatores.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 95,
    symbol: "Am",
    name: "Amerício",
    atomic_mass: 243.06138,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f⁷ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O amerício é um actinídeo radioativo, usado em detectores de fumaça.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 96,
    symbol: "Cm",
    name: "Cúrio",
    atomic_mass: 247.07035,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O cúrio é um actinídeo altamente radioativo, usado em geradores termoelétricos.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 97,
    symbol: "Bk",
    name: "Berquélio",
    atomic_mass: 247.07031,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f⁹ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O berquélio é um actinídeo radioativo, produzido em pequenas quantidades para pesquisa.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 98,
    symbol: "Cf",
    name: "Califórnio",
    atomic_mass: 251.07959,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f¹⁰ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O califórnio é um actinídeo altamente radioativo, usado como fonte de nêutrons.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 99,
    symbol: "Es",
    name: "Einstênio",
    atomic_mass: 252.08298,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f¹¹ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O einstênio é um actinídeo radioativo, produzido em quantidades mínimas para pesquisa.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 100,
    symbol: "Fm",
    name: "Férmio",
    atomic_mass: 257.09511,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f¹² 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O férmio é um actinídeo radioativo, produzido por bombardeamento nuclear.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 101,
    symbol: "Md",
    name: "Mendelévio",
    atomic_mass: 258.09843,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f¹³ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O mendelévio é um actinídeo radioativo, nomeado em homenagem a Dmitri Mendeleev.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 102,
    symbol: "No",
    name: "Nobélio",
    atomic_mass: 259.101,
    group: 3,
    period: 7,
    block: "f",
    electron_configuration: "[Rn] 5f¹⁴ 7s²",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O nobélio é um actinídeo radioativo, nomeado em homenagem a Alfred Nobel.",
    color: "#d8b4fe",
  },
  {
    atomic_number: 103,
    symbol: "Lr",
    name: "Laurêncio",
    atomic_mass: 266.12,
    group: 3,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: 1.3,
    phase: "Sólido",
    category: "Actinídeo",
    description:
      "O laurêncio é o último elemento da série dos actinídeos, altamente radioativo.",
    color: "#d8b4fe",
  },

  {
    atomic_number: 104,
    symbol: "Rf",
    name: "Rutherfórdio",
    atomic_mass: 267.122,
    group: 4,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: null,
    phase: "Sólido",
    category: "Metal de Transição",
    description:
      "Elemento sintético altamente radioativo. Primeiro transactinídeo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 105,
    symbol: "Db",
    name: "Dúbnio",
    atomic_mass: 268.126,
    group: 5,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: null,
    phase: "Sólido",
    category: "Metal de Transição",
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 106,
    symbol: "Sg",
    name: "Seabórgio",
    atomic_mass: 269.128,
    group: 6,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: null,
    phase: "Sólido",
    category: "Metal de Transição",
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 107,
    symbol: "Bh",
    name: "Bóhrio",
    atomic_mass: 270.133,
    group: 7,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: null,
    phase: "Sólido",
    category: "Metal de Transição",
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 108,
    symbol: "Hs",
    name: "Hássio",
    atomic_mass: 269.1339,
    group: 8,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: null,
    phase: "Sólido",
    category: "Metal de Transição",
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 109,
    symbol: "Mt",
    name: "Meitnério",
    atomic_mass: 278.156,
    group: 9,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d⁷ 7s²", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal de Transição", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 110,
    symbol: "Ds",
    name: "Darmstádtio",
    atomic_mass: 281.164,
    group: 10,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d⁹ 7s¹", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal de Transição", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 111,
    symbol: "Rg",
    name: "Roentgênio",
    atomic_mass: 282.169,
    group: 11,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal de Transição", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 112,
    symbol: "Cn",
    name: "Copernício",
    atomic_mass: 283.179,
    group: 12,
    period: 7,
    block: "d",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", // Predicted
    electronegativity: null,
    phase: "Gás", // Predicted (unusual for this group, but relativistic effects)
    category: "Metal de Transição", // Predicted (sometimes classified as Pós-Transição) - Let's stick to Transição for consistency in d-block color.
    description: "Elemento sintético altamente radioativo.",
    color: "#bae6fd",
  },
  {
    atomic_number: 113,
    symbol: "Nh",
    name: "Nihônio",
    atomic_mass: 286.182,
    group: 13,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal Pós-Transição", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#d9f99d",
  },
  {
    atomic_number: 114,
    symbol: "Fl",
    name: "Fleróvio",
    atomic_mass: 289.19,
    group: 14,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", // Predicted
    electronegativity: null,
    phase: "Líquido", // Predicted (relativistic effects)
    category: "Metal Pós-Transição", // Predicted (relativistic effects suggest noble-gas-like properties, but classified here by position)
    description: "Elemento sintético altamente radioativo.",
    color: "#d9f99d",
  },
  {
    atomic_number: 115,
    symbol: "Mc",
    name: "Moscóvio",
    atomic_mass: 290.196,
    group: 15,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal Pós-Transição", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#d9f99d",
  },
  {
    atomic_number: 116,
    symbol: "Lv",
    name: "Livermório",
    atomic_mass: 293.205,
    group: 16,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted
    category: "Metal Pós-Transição", // Predicted (might have some semimetal/nonmetal traits) - Keeping Pós-Transição color.
    description: "Elemento sintético altamente radioativo.",
    color: "#d9f99d",
  },
  {
    atomic_number: 117,
    symbol: "Ts",
    name: "Tenessino",
    atomic_mass: 294.211,
    group: 17,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", // Predicted
    electronegativity: null,
    phase: "Sólido", // Predicted (might be liquid or gas) - Solid is a common prediction.
    category: "Halogênio", // Predicted
    description: "Elemento sintético altamente radioativo.",
    color: "#fbcfe8",
  },
  {
    atomic_number: 118,
    symbol: "Og",
    name: "Oganessônio",
    atomic_mass: 295.216,
    group: 18,
    period: 7,
    block: "p",
    electron_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", // Predicted
    electronegativity: null,
    phase: "Gás", // Predicted (though could be liquid/solid due to relativistic effects) - Keeping Gas based on group.
    category: "Gás Nobre", // Predicted
    description:
      "Elemento sintético altamente radioativo. O último elemento conhecido.",
    color: "#bfdbfe",
  },
];

export default elementosDaTabelaPeriodica;
